### ISSUE TITLE
Document range of opacity values

### ISSUE THREAD

**Issue by krlmlr** [emiapwil/glassy-gnome#1]
I'm fine with using `gsettings` and `dconf-tool`, but the README doesn't tell anything about the valid range of opacity values. My guess is 0-100 (0x64).

On that note: If I hit Super+0 for a fully opaque window, say, three times, I need to hit Super+9 *four* times until the window starts becoming transparent.

**Comment by emiapwil** [comment]
Hi Kirill,

Thanks for your comment.  You are right about the range of opacity
values.  I'll update the documentation and fix the bug as soon as possible.

**Comment by emiapwil** [comment]
Fixed by [this commit](https://github.com/emiapwil/glassy-gnome/commit/202449218240b80c8b6e9b1013f4ff6aa0117035).
