### ISSUE TITLE
glassy-gnome cause Google Chrome Browser maximize exception

### ISSUE THREAD

**Issue by andreahbji** [emiapwil/glassy-gnome#10]
system：ubuntu gnome 16.10 LTS,GNOME 3.18

GPU ：use INTEL GRAPHICS UPDATE TOOL FOR LINUX install GPU driver，pls refer [安装显卡驱动.txt](https://github.com/emiapwil/glassy-gnome/files/1058219/default.txt)

steps：

1. chrome browser uncheck "use system title-bar and border"
2. install glassy-gnome by Gnome-Tweak at https://extensions.gnome.org
3. start glassy-gnome，then maximize chrome browser , 100% exception.
![glassy_gnome_issue](https://user-images.githubusercontent.com/2755606/26882547-458f0f24-4bcd-11e7-895d-6aa01ab4b01b.gif)

note：

chrome browser maximize can work when check "use system title-bar and border"

**Comment by emiapwil** [comment]
Hello! Thanks for your feedback. I did a little digging and found [a post](https://askubuntu.com/questions/830828/chrome-bug-when-maximizing) reporting the same error which may indicate that this is a bug related to the integration of GNOME and Chrome.

I'm still downloading the image so I can try to replicate the bug later today. Before that, could you please confirm this bug does NOT occur when glassy-gnome is disabled? Thanks!

**Comment by smartxdcn** [comment]
ubuntu 17.10 ,gnome-shell 3.26.2,The same problem occurs
