### ISSUE TITLE
Set Default Transparencies? 

### ISSUE THREAD

**Issue by aidrocsid** [emiapwil/glassy-gnome#13]
I was wondering if there's a command that can be used to set the default transparency of active and inactive windows. I didn't see anything in the readme.

**Comment by stratigos** [comment]
@aidrocsid apparently you can use `gsettings`, as per the [Window Filters](https://github.com/emiapwil/glassy-gnome#window-filters) section in the README.

I am currently having trouble getting this to work throughout my system, though. The wildcard expression is applied to every single window for me, even with patterns for `Terminal`, `Firefox`, etc. If I take the wildcard out, then _nothing_ is applied, and I cant change any transparencies. 

It does work to set a default transparency, active and inactive, system wide.
