### ISSUE TITLE
Incorrect Patterns?

### ISSUE THREAD

**Issue by mgtlake** [emiapwil/glassy-gnome#14]
On my machine, I had to change `'Terminal' `to` 'Gnome-terminal'` for the settings change to work. 

I'm running Ubuntu 18.04 with Gnome 3.28.3.

Additionally, the looking class link in the README seems to be down.

**Comment by stratigos** [comment]
I am using same version of `gnome-shell`, and also cant get _any_ patterns to work, except the wildcard. 

If the wildcard is not present, none of my windows respond to transparency values.

With the wildcard present, only that rule is applied to every window. Custom settings per-pattern are not applied.

Here is an example setting I have:

```
[
  (['Terminal'], 0x64, 0x64, 0x0a),
  (['Firefox', 'Sublime'], 0x64, 0x64, 0x05),
  (['gedit'], 0x5a, 0x50, 0x0a),
  (['.*'], 0x64, 0x50, 0x05)
]
```
Ive also tried messing with the orderings, tweaking the patterns, etc. Its wildcard-pattern or nothing at all for me.

**Comment by matthew-lake** [comment]
@stratigos Have you tried the names given by Looking Glass (alt-F2 -> 'lg')? I found that they differed from those given by `xwininfo`. For example, I needed to change `['Terminal']` tot `['Gnome-terminal']` in my config.

**Comment by stratigos** [comment]
@matthew-lake bingo! You got it, that was the problem for me. Its also case sensitive, so `gedit` wasnt caught, but `Gedit` is. 

I pasted a small excerpt of my settings, I had custom setting for about 20 different windows, which now all work exactly as I want them to! (`Sublime_text`, not `Sublime Text`, etc... :sweat_smile: )
