### ISSUE TITLE
keyboard shortcuts dont work

### ISSUE THREAD

**Issue by psykotik1** [emiapwil/glassy-gnome#17]
keyboard shortcuts to increase/decrease opacity have no effect, arch linux w/ gnome 3.30

**Comment by psykotik1** [comment]
here is a snippet from journalctl -f, when pressing the hotkey: 

Jan 07 22:09:08 zephyr gnome-shell[16947]: JS ERROR: ReferenceError: active_workspace_index is not defined
                                           is_active_window@/home/johnny/.local/share/gnome-shell/extensions/glassygnome@emiapwil/extension.js:76:12
                                           get_active_window/active_windows<@/home/johnny/.local/share/gnome-shell/extensions/glassygnome@emiapwil/extension.js:81:16
                                           get_active_window@/home/johnny/.local/share/gnome-shell/extensions/glassygnome@emiapwil/extension.js:80:26
                                           reset_window_opacity@/home/johnny/.local/share/gnome-shell/extensions/glassygnome@emiapwil/extension.js:264:15

**Comment by psykotik1** [comment]
can decrease/increase opacity when changing the mod key to alt, but switching between windows resets transparency

**Comment by psykotik1** [comment]
started working again after disabling extensions with gsettings, then re-enabling, dont know what the deal is!

**Comment by emiapwil** [comment]
Sorry for the late reply. Seems like the "`active_workspace_index` is not defined" could be the issue (maybe not covering some corner case, I don't know for sure). I'll see what I can do.

**Comment by eduncan911** [comment]
For the record, it's working for me on Flatpak, Pop_OS 18.04 and 19.04 using version `v16`

**Comment by emiapwil** [comment]
@eduncan911 It's good to know. Thanks :)
