### ISSUE TITLE
Unshading a window won't restore it to non-transparent state

### ISSUE THREAD

**Issue by ipaq3870** [emiapwil/glassy-gnome#2]
Hi,

On gnome 3.18, unshading a previously shaded window by double tapping the window title bar will result in a window that is still transparent. I propose the following patch that seems to have fixed my problem:

```
--- extension.js.0	2015-09-25 11:43:42.000000000 +0800
+++ extension.js	2016-04-14 10:12:11.687902943 +0800
@@ -20,7 +20,7 @@
 
 var settings, filters, activated;
 
-var on_window_created, on_restacked;
+var on_window_created, on_restacked, on_focused;
 
 var setting_signals;
 
@@ -311,6 +311,7 @@
 
     on_window_created = global.display.connect('window-created', glassify);
     on_restacked = global.screen.connect('restacked', glassify);
+    on_focused = global.display.connect('notify::focus-window', glassify);
 
     connect_signals();
     create_label();
```

**Comment by emiapwil** [comment]
Thanks @ipaq3870 for the patch!  I will try to replicate the scenario as soon as possible and accept the patch after that.

**Comment by emiapwil** [comment]
Hello @ipaq3870, I have tested the patch and it is working perfectly.  Do you want to make a pull request so that your contribution can be honored?

**Comment by ipaq3870** [comment]
Hi @emiapwil, never mind about the pull request - it's just 2 lines of code. I'll be happy if you could publish a patched version on extension.gnome.org to make my local patch management easier.

**Comment by emiapwil** [comment]
@ipaq3870 The [latest commit](https://github.com/emiapwil/glassy-gnome/commit/227fb29f774b5243ef1b59b380012663ec0655a5) contains your patch.  I have also updated the patched extension to extension.gnome.org but it's still under review.

Again, thanks for the help!

**Comment by emiapwil** [comment]
@ipaq3870 The updated extension can be obtained from [extensions.gnome.org](https://extensions.gnome.org/extension/982/glassy-gnome/) now.
