### ISSUE TITLE
Some UI widgets always transparent

### ISSUE THREAD

**Issue by ipaq3870** [emiapwil/glassy-gnome#4]
Hi,

Some UI widgets are always transparent even if it is in the foreground, for e.g., drop down menus, context menus, splash screens, tool tips, etc. Depending on the transparency settings, the themes being used and the personal tastes, the final display could be something cool to something really illegible.

I made the following quick fix that is not quite ideal but then again it works for me. Need to apply the patch from issue 3 first.

```
--- extension.js.2  2016-04-18 16:52:24.785771615 +0800
+++ extension.js.3  2016-04-18 16:56:56.764140355 +0800
@@ -52,6 +52,14 @@
             offset:     0
         };
     }
+    let window_type = meta_win.get_window_type();
+    if (window_type == Meta.WindowType.DROPDOWN_MENU ||
+        window_type == Meta.WindowType.POPUP_MENU ||
+        window_type == Meta.WindowType.SPLASHSCREEN ||
+        window_type == Meta.WindowType.TOOLTIP ||
+        window_type == Meta.WindowType.OVERRIDE_OTHER) {
+            return;
+        }
     let window_class = meta_win.get_wm_class();
     for (let i in filters) {
         let filter = filters[i];
```

**Comment by emiapwil** [comment]
Is it possible a screenshot be provided for this issue?

By the way I might be a little busy in the following weeks so I might not be able to respond in time.  Sorry for the inconvenience.

**Comment by ipaq3870** [comment]
![1](https://cloud.githubusercontent.com/assets/1582108/14600124/ad616066-058d-11e6-800d-f7487230ff6c.png)
![2](https://cloud.githubusercontent.com/assets/1582108/14600123/ad60c188-058d-11e6-848f-978dd2d9021c.png)

**Comment by emiapwil** [comment]
@ipaq3870 Hello!  Sorry that I didn't do much about this issue for a while.  I now introduced a new option trying to be flexible enough for different people's tastes.  In your use case, you can use the following command to achieve 100% opaque menus/tool bars/splash screens:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/glassygnome@emiapwil/schemas \
          set org.gnome.shell.extensions.glassy-gnome mix-ratio 255`
