### ISSUE TITLE
Icon toggle and Default Opacity questions

### ISSUE THREAD

**Issue by hhhorb** [emiapwil/glassy-gnome#6]
I mostly opened this issue to say thank you! Works great.

I've hacked at the .js to remove the icon, but when you create a GUI that would be a nice feature (show/hide icon option).

Thanks again, this is perfect!

**Comment by emiapwil** [comment]
@hhhorb Glad you like it! ^_^

**Comment by hhhorb** [comment]
Hey, I don't wan't to open a new issue if it's not necessary so I'll tag it on here... I have active windows set to open at 100% opacity, which works great, but if I switch away and back the window resets to 90% (the original value for the extension). Is that set in the js files somewhere, or is there a schema I can add so every active window is opaque, whether or not it's a new window?

**Comment by emiapwil** [comment]
@hhhorb 

OK I can confirm the opacity bug now, the problem is that the opacity is not correctly set for new windows.  You can use the window filters to set the opacity for active/inactive windows.  In your case, please change the `byte 0x5f`(hex for 95) right after `['.*']` to `byte 0x64`(hex for 100) and use the command to update the configuration (sorry there's no better way to do that at the moment...).

Let me know if that works.  Thanks for your feedback!

**Comment by emiapwil** [comment]
@hhhorb I believe the issue is solved. Can you please confirm that?  I also update the latest zip file to [gnome extension](https://extensions.gnome.org/extension/982/glassy-gnome/) whose version should be 11.

**Comment by hhhorb** [comment]
Hey, sorry for the delay. I'm in the US so yesterday was a party, plus our project (BunsenLabs Linux) has a deadline we're hitting so I'm busy.

I've been running gnome-shell 3.14 on Debian jessie, but I'm getting ready to set up 3.20 in another partition so I can test. Till I post back, cheers!

**Comment by emiapwil** [comment]
I haven't upgraded to 3.20 yet so it would be great if you can test it.  You may have to add 3.20 to metadata.json to make it work.

Thanks!

**Comment by hhhorb** [comment]
Both Debian testing and unstable are at version 3.20. I tried downloading the zip and bumping the version number, but it won't install.

I'll try something else and post back (probably bot for a few days though).

Cheers!

**Comment by emiapwil** [comment]
Can you try the following steps?
1. `Alt+F2` and type `lg` to enter the LookingGlass tool.
2. Click on the extensions tab and see if the plugin reports any errors.

Thanks!  Really appreciate it!

**Comment by hhhorb** [comment]
It'll be a while, I'm running live-build(s), but sure!

**Comment by hhhorb** [comment]
Found it (I think), the file /schemas/gschemas.compiled is missing.

For those using GNOME 3.14, extensions.gnome.org serves v.3. If you want to remove the panel icon without gnome-tweak or looking-glass reporting errors, comment out or remove line #296 from extension.js

`   /* Main.panel.addToStatusArea('glassygnome_indicator', indicator); * /`



Not bad for an end user who knows NO coding whatsoever, eh? :^D

**Comment by emiapwil** [comment]
Looks like an issue when the repo is directly copied to the extension folder...or the schema should be compiled.  I removed the compiled binary file in a previous commit...I just add it back and could you please see if that solves the problem?

**Comment by hhhorb** [comment]
Fail, I can't get it to install. Maybe the api broke in .20, maybe Debian doesn't have it right, I don't know.

Suggestion... we have 3 issues here, icon toggle, opacity and installation. Leave icon toggle here and split install on .20 and opacity default to two new issues, it's better for search engines when people are trying to troubleshoot.

Second suggestion... don't worry about .20 yet, focus on 3.18, 3.16, 3.14, that's the majority of GNOME users.

Cheers!

Hass

**Comment by emiapwil** [comment]
Yeah GNOME 3 has pissed off a lot of people...

Thanks for the tips~^_^

**Comment by hhhorb** [comment]
^Lol, indeed, and no problem! I like my 3.14 setup so I'll keep using your extension!

**Comment by emiapwil** [comment]
@hhhorb Hi, long time no see!  Gentoo has already upgraded to GNOME 3.20 and I haven't noticed anything broken (probably GNOME team has fixed the bugs?).  It will be much appreciated if you could take a little time and see if it works on Debian as well.  Thanks in advance!

**Comment by hhhorb** [comment]
Sorry for the long delay,  I had a really rough fall and holiday.

I've upgraded to stretch and had keyboard issues and GNOME issues. I removed GNOME, installed LXDE and that's working great. 

I'm afraid I'll have to leave this issue to you for now as I'm busy with other projects. Good luck,  and I'll check back when I next return to GNOME!
