### ISSUE TITLE
universal transparency for all windows

### ISSUE THREAD

**Issue by psykotik1** [emiapwil/glassy-gnome#8]
how can i make all windows have the same transparency whether active or inactive, for a uniform look?

**Comment by emiapwil** [comment]
Below is a script adopted from the configurations in README, you can change the values according to your preferences.  The three parameters are `foreground transparency`, `background transparency` and `transparency-step`.  Hope that helps.

~~~
gsettings --schemadir ~/.local/share/gnome-shell/extensions/glassygnome@emiapwil/schemas \
          set org.gnome.shell.extensions.glassy-gnome filters \
          "[
              (['.*'], byte 0x5f, byte 0x50, byte 0x05)
          ]"
~~~

**Comment by psykotik1** [comment]
thank you very much, that is just what i am looking for
